### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by Wavesonics** [skolson/KmpIO#2]
This would be great to get published to Maven Central, looks like a really handy library.

**Comment by stephanepechard** [comment]
I agree, this would give it visibility and usage, which is needed to ensure long-term stability.
Let me know if help is needed in order to make the publication.

**Comment by skolson** [comment]
Ok, I'll start the publish process up and post progress/status here. Thanks!

**Comment by skolson** [comment]
Publish is complete today and should be usable: io.github.skolson:kmp-io. I'll update the readme after using it from maven in my stuff. If that all works I'll close this issue,

**Comment by skolson** [comment]
It looks like the maven publish is successful. Readme is updated.
