### ISSUE TITLE
iosSimulatorArm64 target

### ISSUE THREAD

**Issue by VitalyPeryatin** [skolson/KmpIO#4]
Hi,
I appreciate this library. Could you add the `iosSimulatorArm64()` target too?

**Comment by VitalyPeryatin** [comment]
if I could somehow support it, I would transfer a little money after the lib update

**Comment by skolson** [comment]
I'll also be adding linuxx64 in the next point release. Also will refresh kotlin and gradle, and transition to gradle version catalog in the build.

**Comment by skolson** [comment]
Added in 0.1.5 release. Should be published to maven by 12/15/2023
