### ISSUE TITLE
Needs license clarification

### ISSUE THREAD

**Issue by gandrewstone** [skolson/KmpIO#7]
There appears to be no license on the project yet (or maybe I just can't find one).
Having a file in the project root called COPYING with your license is pretty standard, AFAICT.

**Comment by gandrewstone** [comment]
I see in build.gradle.kts its marked as apache-2.0:
        summary = "Kotlin Multiplatform API for basic File I/O"
        homepage = githubUrl
        license = "Apache 2.0"

I still think that it would be better to specify the license in a separate file though to make it easier to find.

**Comment by skolson** [comment]
Yup, I'll add a LICENSE.md in the next commit.

**Comment by skolson** [comment]
Lol when 0.1.6 was published to maven, I missed doing the push. Push is now done.
